### ISSUE TITLE
removing metabolites based on too many missing values

### ISSUE THREAD

**Issue by sunta3iouxos** [antonvsdata/notame#27]
Dear all,
Thank you for this passage. I tried to find a relative information both on "Random forest-based imputation" publication and on the "notame"one and I could not.
The question is how this pipeline handles metabolites with excessive missing data?
The standard rule is the 80% and you are out.
What is your take on this? does the random forest approach decide also on this?
Thank you

**Comment by antonvsdata** [comment]
Hi, sorry for the delayed response. I notame, you can use the function `flag_detection()` to flag features based on the proportion of missing values, in either QCs or in specified sample groups in your dataset. The default limit< 70% non-missing values in QC samples and the feature is flagged.

For imputation, you can either use `impute_simple()` for multiple simple imputation strategies, or use `impute_rf()` for random forest-based imputation.

The preprocessing vignette has more detailed information.
